---
angular_resolution: 5
copy_config_to: ${HOME}/ugd/best_models/experimental/closedform_hqs/2021-04-16-10-31-20/config.yml
training:
  optimizer: !Adam
    learning_rate: !PiecewiseConstantDecay
      boundaries: 
        - 500000
      values:
        - 1.0e-3
        - 1.0e-4
    beta_2: 0.98
    epsilon: 1.e-5 
    clipvalue: 1.
  callbacks:
    - !ModelCheckpoint
      filepath: ${TEMPDIR}/ugd_models/experimental/closedform_hqs/2021-04-16-10-31-20/{epoch:02d}.ckpt
      save_weights_only: true
      verbose: true
    - !ModelCheckpoint
      filepath: ${HOME}/ugd/best_models/experimental/closedform_hqs/2021-04-16-10-31-20/best.tf
      save_best_only: true
      verbose: true
    - !Tensorboard
      log_dir: ${HOME}/ugd/tensorboard/experimental/closedform_hqs/2021-04-16-10-31-20
  epochs: 180
  compile: true
model: !PixelwiseModel
  acquisition_reconstruction: !PixelwiseAcquisitionReconstruction
    generator: !PixelwiseMatrixGenerator
      modulation_layers:
        - !UniformModulation
            number_of_shots: 1
        - !CFAModulation
            mode: bayer
    reconstructor: !PixelwiseClosedFormHQS
      proximals: !BlocksFromResiduals
        residuals: !ResProxes
          count: 12
          number_of_convolutions: 4
        delta_initial_value: 0.1
      mu_initial_value: 1.0
datasets:
  train:
    file_descriptions:
    - root_dir: ${DATADIR}/kalantari-dataset/training/original-kalantari
      format: lf_{v+1+(8-angular_resolution)//2}_{u+1+(8-angular_resolution)//2}.png
    - root_dir: ${DATADIR}/kalantari-dataset/training/stanford-subset
      format: lf_{v+1+(8-angular_resolution)//2}_{u+1+(8-angular_resolution)//2}.png
    - root_dir: ${DATADIR}/kalantari-dataset/test/extra
      names_to_ignore:
      - IMG_1554_eslf
      - IMG_1555_eslf
      format: lf_{v+1+(8-angular_resolution)//2}_{u+1+(8-angular_resolution)//2}.png
    - root_dir: ${TEMPDIR}/StanfordLytro
      format: lf_{v+1+(8-angular_resolution)//2}_{u+1+(8-angular_resolution)//2}.png
      names_to_ignore:
      - flower_plants_55_eslf
      - flower_plants_56_eslf
    options:
      batch_size: 16
      prefetch: true
      patch_height: 64
      patch_width: 64
      shuffle_before_extraction: true
      shuffle_after_extraction: true
      buffer_size: 2500
      patch_stride_ratio: 2
  dev:
    file_descriptions:
    - root_dir: ${DATADIR}/linkoping-dataset
      format: TM_{v+1+(7-angular_resolution)//2:02d}_{u+1+(7-angular_resolution)//2:02d}.png
    options:
      batch_size: 16
      prefetch: true
      patch_height: 64
      patch_width: 64
  test:
    file_descriptions:
    - root_dir: ${DATADIR}/test-dataset
      format: lf_{v+1+(8-angular_resolution)//2}_{u+1+(8-angular_resolution)//2}.png
    options:
      batch_size: 1
